env:
  open:
    test: "test"

fullnameOverride: "devreon-bridge-reporting-host"
replicaCount: 1

initContainer:
  enabled: true

cron:
  enabled: true

version: "2025-07-29-12.05-fix-cors"

imagePullSecrets:
  - name: ecr-registry-secret

ingress:
  enabled: false

route:
  enabled: false

resources: 
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      containerPort: 8080
    - name: grpc
      port: 5037
      containerPort: 5037
  
rbac:
  create: true
  rolename: system:openshift:scc:nonroot  

probes:
  enabled: false


serviceAccount:
  create: true
  annotations: {}

podSecurityContext:
  fsGroup: 65534

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 65534
  # capabilities:
  #   drop:
  #   - ALL

volumes:
  existingSecret:
  # mountPath: /secrets

pvc:
  enabled: false
