{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    app: {{ include "generic.fullname" . }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  {{- if .Values.cron.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  {{- end }}
  {{- if .Values.cron.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cron.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cron.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          labels:
            app: {{ include "generic.fullname" . }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "generic.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ if .Values.cron.restartPolicy }}{{ .Values.cron.restartPolicy }}{{ else }}"OnFailure"{{ end }}
          containers:
            - name: {{ include "generic.fullname" . }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "908052927744.dkr.ecr.ap-southeast-1.amazonaws.com/bridge-reporting/{{ $.Values.fullnameOverride }}:{{ $.Values.version }}"
              imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
              {{- if .Values.customCommand }}
              command:
                {{- toYaml .Values.customCommand | nindent 16 }}
              {{- end }}
{{- if .Values.volumes.existingSecret }}
              volumeMounts:
                - mountPath: {{ .Values.volumes.mountPath | quote }}
                  name: {{ .Values.volumes.existingSecret | quote }}
                  readOnly: true
{{- end }}
              env:
                - name: K8S_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
{{- range $name, $value := .Values.env.open }}
{{- if not (empty $value) }}
                - name: {{ $name }}
                  value: {{ $value }}
{{- end }}
{{- end }}
{{- if .Values.env.open }}
{{- range $name, $value := .Values.env.open }}
{{- if not (empty $value) }}
                - name: {{ $name }}
                  value: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.env.field }}
{{- if not ( empty $value) }}
                - name: {{ $name }}
                  value: {{ $value }}
{{- end }}
{{- end }}
{{- if .Values.env.field }}
{{- range $name, $value := .Values.env.field }}
{{- if not ( empty $value) }}
                - name: {{ $name }}
                  value: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
              {{- if .Values.pvc.enabled }}
              volumeMounts:
                {{- range .Values.pvc.items }}
                - name: {{ .name }} 
                  mountPath: "{{ .mountPath }}"
                  readOnly: {{ .readOnly | default false }}
                {{- end }}
              {{- end }}
              resources:
                {{- if .Values.resources }}
                {{- toYaml .Values.resources | nindent 16 }}
                {{- else }}
                {{- toYaml .Values.resources | nindent 16 }}
                {{- end }}
          {{- if .Values.pvc.enabled }}
          volumes:
          {{- range .Values.pvc.items }}
            - name: {{ .name }}
              persistentVolumeClaim:
                claimName: {{ .name }}
          {{- end }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }} 