{{- $fullName := include "generic.fullname" . -}}
{{- if and .Values.cron .Values.cron.enabled }}
{{- $cronImage := "" -}}
{{- $cronTag := "" -}}
{{- $cronPullPolicy := "" -}}
{{- $cronCommand := "" -}}
{{- $cronVaultEnvPath := "" -}}
{{- if .Values.cron.image -}}
  {{- $cronImage = .Values.cron.image.repository | default .Values.image.repository -}}
  {{- $cronTag = .Values.cron.image.tag | default .Values.image.tag | default .Chart.AppVersion -}}
  {{- $cronPullPolicy = .Values.cron.image.pullPolicy | default .Values.image.pullPolicy -}}
  {{- $cronCommand = .Values.cron.image.customCommand | default .Values.image.customCommand -}}
  {{- $cronVaultEnvPath = .Values.cron.image.vaultEnvPath | default .Values.image.vaultEnvPath -}}
{{- else -}}
  {{- $cronImage = .Values.image.repository -}}
  {{- $cronTag = .Values.image.tag | default .Chart.AppVersion -}}
  {{- $cronPullPolicy = .Values.image.pullPolicy -}}
  {{- $cronCommand = .Values.image.customCommand -}}
  {{- $cronVaultEnvPath = .Values.image.vaultEnvPath -}}
{{- end -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "generic.fullname" . }}-cron
  labels:
    app: {{ include "generic.fullname" . }}-cron
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  {{- if and .Values.cron .Values.cron.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  {{- end }}
  {{- if and .Values.cron .Values.cron.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  {{- end }}
  {{- if and .Values.cron .Values.cron.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if and .Values.cron .Values.cron.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          labels:
            app: {{ include "generic.fullname" . }}-cron
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "generic.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ if and .Values.cron .Values.cron.restartPolicy }}{{ .Values.cron.restartPolicy }}{{ else }}"OnFailure"{{ end }}
          containers:
            - name: {{ include "generic.fullname" . }}-cron
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ $cronImage }}:{{ $cronTag }}"
              imagePullPolicy: {{ $cronPullPolicy }}
              {{- if $cronCommand }}
              command:
                {{- toYaml $cronCommand | nindent 16 }}  
              {{- else if $cronVaultEnvPath }}
              command:
                - sh
                - -c
                - source {{ $cronVaultEnvPath }} && /usr/bin/supervisord -s -n -c /etc/supervisor/conf.d/supervisord.conf
              {{- end }}
{{- if .Values.volumes.existingSecret }}
              volumeMounts:
                - mountPath: {{ .Values.volumes.mountPath | quote }}
                  name: {{ .Values.volumes.existingSecret | quote }}
                  readOnly: true
{{- end }}
              env:
                - name: K8S_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
{{- range $name, $value := .Values.env.open }}
{{- if not (empty $value) }}
                - name: {{ $name | quote }}
                  value: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if and .Values.cron .Values.cron.env .Values.cron.env.open }}
{{- range $name, $value := .Values.cron.env.open }}
{{- if not (empty $value) }}
                - name: {{ $name | quote }}
                  value: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- range $name, $value := .Values.env.field }}
{{- if not ( empty $value) }}
                - name: {{ $name | quote }}
                  valueFrom:
                    fieldRef:
                      fieldPath: {{ $value | quote }}
{{- end }}
{{- end }}
{{- if and .Values.cron .Values.cron.env .Values.cron.env.field }}
{{- range $name, $value := .Values.cron.env.field }}
{{- if not ( empty $value) }}
                - name: {{ $name | quote }}
                  valueFrom:
                    fieldRef:
                      fieldPath: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
              {{- if .Values.pvc.enabled }}
              volumeMounts:
                {{- range .Values.pvc.items }}
                - name: {{ .name }} 
                  mountPath: "{{ .mountPath }}"
                  readOnly: {{ .readOnly | default false }}
                {{- end }}
              {{- end }}
              resources:
                {{- if and .Values.cron .Values.cron.resources }}
                {{- toYaml .Values.cron.resources | nindent 16 }}
                {{- else }}
                {{- toYaml .Values.resources | nindent 16 }}
                {{- end }}
          {{- if .Values.pvc.enabled }}
          volumes:
          {{- range .Values.pvc.items }}
            - name: {{ .name }}
              persistentVolumeClaim:
                claimName: {{ .name }}
          {{- end }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }} 