{{- if .Values.ingress.enabled -}}
{{- $fullName := include "generic.fullname" . -}}
{{- $svcPort := .Values.service.ports -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.ingress.paths }}
          {{- range $.Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "generic.fullname" $ }}
                port:
                  number: {{ (index $.Values.service.ports 0).port }}
          {{- end }}
          {{- else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "generic.fullname" $ }}
                port:
                  number: {{ (index $.Values.service.ports 0).port }}
          {{- end }}
    {{- end }}
{{- end }}