apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    app: {{ include "generic.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
{{- end }}
  selector:
    app: {{ include "generic.fullname" . }}
